# Generated by Django 6.0.6 on 2026-06-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Đơn đặt phòng', 'verbose_name_plural': 'Các đơn đặt phòng'},
        ),
        migrations.AlterModelOptions(
            name='roomcategory',
            options={'verbose_name': 'Loại phòng', 'verbose_name_plural': 'Các loại phòng'},
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default='Phòng sang trọng với đầy đủ tiện nghi.'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
