# Generated by Django 6.0.6 on 2026-06-30 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_roomimage_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tiền cọc (50%)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ thanh toán cọc'), ('CONFIRMED', 'Đã cọc - Giữ phòng'), ('CHECKED_IN', 'Khách đang ở'), ('CHECKED_OUT', 'Đã trả phòng'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnp_txn_ref', models.CharField(max_length=100, unique=True, verbose_name='Mã giao dịch VNPay')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền đã GD')),
                ('vnp_response_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mã phản hồi VNPay')),
                ('is_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pay_date', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='booking.booking')),
            ],
            options={
                'verbose_name': 'Đơn đặt phòng',
                'verbose_name_plural': 'Các đơn đặt phòng',
            },
        ),
    ]
