# Generated by Django 6.0.6 on 2026-07-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_deposit_amount_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Thanh toán VNPay', 'verbose_name_plural': 'Lịch sử thanh toán'},
        ),
    ]
