# Generated by Django 6.0.6 on 2026-07-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_check_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ vào thực tế'),
        ),
        migrations.AddField(
            model_name='booking',
            name='actual_check_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ ra thực tế'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_requested',
            field=models.BooleanField(default=False, verbose_name='Khách yêu cầu hủy'),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
