# Generated by Django 6.0.6 on 2026-07-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_actual_check_in_booking_actual_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cccd_image',
            field=models.ImageField(blank=True, null=True, upload_to='cccd/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_cccd',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số CCCD / CMND / Passport'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên khách lưu trú'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại khách'),
        ),
    ]
