# Generated by Django 6.0.6 on 2026-07-05 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_conversation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã KM')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Phần trăm (%)'), ('FIXED', 'Số tiền (VNĐ)')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Mức giảm')),
                ('valid_from', models.DateTimeField(verbose_name='Bắt đầu')),
                ('valid_to', models.DateTimeField(verbose_name='Kết thúc')),
                ('usage_limit', models.IntegerField(default=100)),
                ('used_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên gói giá (VD: Tiêu chuẩn, Kèm ăn sáng)')),
                ('includes_breakfast', models.BooleanField(default=False, verbose_name='Bao gồm ăn sáng')),
                ('cancellation_policy', models.CharField(choices=[('NON_REFUNDABLE', 'Không hoàn tiền'), ('FREE_CANCELLATION', 'Hủy miễn phí')], max_length=20)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Giảm giá % so với giá gốc', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sự kiện (VD: Lễ 30/4, Tết)')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Hệ số nhân (VD: 1.5 = Tăng 50%)', max_digits=4)),
                ('is_weekend_only', models.BooleanField(default=False, verbose_name='Chỉ tăng cuối tuần (T6, T7, CN)')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tiền được giảm'),
        ),
        migrations.AddField(
            model_name='booking',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.coupon', verbose_name='Mã KM áp dụng'),
        ),
        migrations.AddField(
            model_name='booking',
            name='rate_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.rateplan', verbose_name='Gói giá'),
        ),
        migrations.CreateModel(
            name='RoomDailyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('override_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá ghi đè')),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.roomcategory')),
            ],
            options={
                'verbose_name': 'Giá tùy chỉnh theo ngày',
                'unique_together': {('room_category', 'date')},
            },
        ),
    ]
