# Generated by Django 6.0.6 on 2026-07-14 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_coupon_rateplan_seasonalpricing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Phòng', 'verbose_name_plural': 'Danh sách phòng'},
        ),
        migrations.AddField(
            model_name='room',
            name='housekeeping_status',
            field=models.CharField(choices=[('CLEAN', 'Sạch sẽ - Sẵn sàng đón khách'), ('DIRTY', 'Chưa dọn - Khách vừa check-out'), ('MAINTENANCE', 'Đang bảo trì/Sửa chữa')], default='CLEAN', max_length=20, verbose_name='Tình trạng dọn dẹp'),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.roomcategory', verbose_name='Thuộc loại phòng'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(default='Phòng sang trọng với đầy đủ tiện nghi.', verbose_name='Mô tả thêm'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Còn trống'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Số phòng'),
        ),
    ]
