# Generated by Django 6.0.6 on 2026-07-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_room_options_room_housekeeping_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonalpricing',
            name='price_multiplier',
        ),
        migrations.AddField(
            model_name='seasonalpricing',
            name='percent_adjustment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Nhập số dương để Tăng giá (VD: 50 là tăng 50%). Nhập số âm để Giảm giá (VD: -20 là giảm 20%)', max_digits=5, verbose_name='Mức điều chỉnh (%)'),
        ),
        migrations.AlterField(
            model_name='rateplan',
            name='cancellation_policy',
            field=models.CharField(choices=[('FLEXIBLE', 'Tiêu chuẩn (Bảo lưu cọc)'), ('NON_REFUNDABLE', 'Không hoàn tiền (Mất cọc)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='seasonalpricing',
            name='is_weekend_only',
            field=models.BooleanField(default=False, verbose_name='Chỉ tăng/giảm cuối tuần (T6, T7, CN)'),
        ),
    ]
