# Generated by Django 6.0.6 on 2026-07-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_remove_seasonalpricing_price_multiplier_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomDailyRate',
        ),
    ]
