"""
Django settings for QLKhachSan project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lt%y=p-z@-1ox4@-&kp37lv%xo2kx$)5re$6q=cp^j!)6&@%2n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'booking',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'QLKhachSan.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'QLKhachSan.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

#------------------------------------------------------Khương thêm
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
#


# Cấu hình giao diện cho Unfold
UNFOLD = {
    "SITE_TITLE": "Hệ thống Khách sạn",
    "SITE_HEADER": "Quản lý Booking",
    "SIDEBAR": {
        "show_search": True,  # Bật thanh tìm kiếm
        "show_all_applications": True, # Hiển thị menu mặc định nếu quên cấu hình
        "navigation": [
            {
                "title": "QUẢN LÝ ĐẶT PHÒNG",
                "separator": True, # Đường kẻ ngang phân cách
                "items": [
                    {
                        "title": "Danh sách Phòng",
                        "icon": "bed", # Tên icon từ Material Symbols
                        "link": "/admin/booking/room/",
                    },
                    {
                        "title": "Loại Phòng",
                        "icon": "hotel_class",
                        "link": "/admin/booking/roomcategory/",
                    },
                    {
                        "title": "Đơn Đặt Phòng",
                        "icon": "book_online",
                        "link": "/admin/booking/booking/",
                    },
                ],
            },
            {
                "title": "QUẢN TRỊ HỆ THỐNG",
                "separator": True,
                "items": [
                    {
                        "title": "Người dùng",
                        "icon": "people",
                        "link": "/admin/auth/user/",
                    },
                    {
                        "title": "Phân quyền (Groups)",
                        "icon": "admin_panel_settings",
                        "link": "/admin/auth/group/",
                    },
                ],
            },
        ],
    },
}

SITE_ID = 1
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)
LOGIN_REDIRECT_URL = '/' # Đăng nhập xong thì về trang chủ
LOGOUT_REDIRECT_URL = '/'
# Cho phép chuyển hướng thẳng sang Google mà không cần qua trang xác nhận
SOCIALACCOUNT_LOGIN_ON_GET = True